Add failover when songbook generation fails
Sometimes the For-mand breaks the songbook, this shouldn't affect our
agile development

diff --git a/.github/workflows/node.yml b/.github/workflows/node.yml
--- a/.github/workflows/node.yml
+++ b/.github/workflows/node.yml
@@ -22,8 +22,18 @@ jobs:
           repository: f-klubben/sangbog
           path: sangbog
 
-      - name: Build songs
-        run: python util/build_songs.py
+      - name: Build songs (with failover)
+        run: |
+          set -e
+          echo "Building songs..."
+          if ! python util/build_songs.py; then
+            echo "Build songs failed — creating empty file as fallback."
+            mkdir -p build/dist
+            touch pages/songbook/songs.json
+          fi
+      
+      #- name: Build songs
+      #run: python util/build_songs.py
 
       - name: Use Node.js
         uses: actions/setup-node@v4
